### ISSUE TITLE
inference error : No module named 'models'

### ISSUE THREAD

**Issue by niteshkumarmpft** [rajesh-bhat/dhs_summit_2019_image_captioning#1]
Is there any means to run only the inference part, as the module is throwing up an error No module named 'models'.

Can you help me resolve this particular issue

**Comment by rajesh-bhat** [comment]
@niteshkumarmpft  in which part of the code are you facing the issue?

**Comment by niteshkumarmpft** [comment]
There is no models.py file as a separate file. It was present in the cells. I managed to get it. 

So thtat problem got fixed. But for inference, is there any way of getting the model file

**Comment by rajesh-bhat** [comment]
@niteshkumarmpft you can find the trained model here: https://drive.google.com/file/d/1wBzn3T_u1mEVoz1isG__vTzNXoq9T4Fl/view?usp=sharing

I have added this info in the notebook as well.
